In [1]:
import pandas as pd

In [4]:
#lendo o arquivo CSV
livros = pd.read_csv("Kindle_data-v2.csv")

#qtde de linhas e colunas do DataFrame
livros.shape

(133102, 16)

In [5]:
livros

,asin,title,author,soldBy,imgUrl,productURL,stars,reviews,price,isKindleUnlimited,category_id,isBestSeller,isEditorsPick,isGoodReadsChoice,publishedDate,category_name
0,B00TZE87S4,Adult Children of Emotionally Immature Parents...,Lindsay C. Gibson,Amazon.com Services LLC,https://m.media-amazon.com/images/I/713KZTsaYp...,https://www.amazon.com/dp/B00TZE87S4,4.8,0,9.99,False,6,True,False,False,2015-06-01,Parenting & Relationships
1,B08WCKY8MB,"From Strength to Strength: Finding Success, Ha...",Arthur C. Brooks,Penguin Group (USA) LLC,https://m.media-amazon.com/images/I/A1LZcJFs9E...,https://www.amazon.com/dp/B08WCKY8MB,4.4,0,16.99,False,6,False,False,False,2022-02-15,Parenting & Relationships
2,B09KPS84CJ,Good Inside: A Guide to Becoming the Parent Yo...,Becky Kennedy,HarperCollins Publishers,https://m.media-amazon.com/images/I/71RIWM0sv6...,https://www.amazon.com/dp/B09KPS84CJ,4.8,0,16.99,False,6,False,True,False,2022-09-13,Parenting & Relationships
3,B07S7QPG6J,Everything I Know About Love: A Memoir,Dolly Alderton,HarperCollins Publishers,https://m.media-amazon.com/images/I/71QdQpTiKZ...,https://www.amazon.com/dp/B07S7QPG6J,4.2,0,9.95,True,6,False,True,False,2020-02-25,Parenting & Relationships
4,B00N6PEQV0,The Seven Principles for Making Marriage Work:...,John Gottman,Random House LLC,https://m.media-amazon.com/images/I/813o4WOs+w...,https://www.amazon.com/dp/B00N6PEQV0,4.7,0,13.99,False,6,False,False,False,2015-05-05,Parenting & Relationships
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133097,B0C3SJDLK8,Anna Karenina,Leo Tolstoy,De Marque,https://m.media-amazon.com/images/I/61RXEyMctk...,https://www.amazon.com/dp/B0C3SJDLK8,4.7,0,0.00,False,29,True,False,False,2023-09-15,Nonfiction
133098,B09DW752Y1,Scary Smart: Scary Smart: The Future of Artifi...,Mo Gawdat,Amazon.com Services LLC,https://m.media-amazon.com/images/I/71tjf6R-Wa...,https://www.amazon.com/dp/B09DW752Y1,4.4,0,9.99,False,29,False,False,False,2021-09-30,Nonfiction
133099,B0CFWHPJTN,The Count of Monte Cristo: The Original Unabri...,Alexandre Dumas,De Marque,https://m.media-amazon.com/images/I/71zcCb5Pvu...,https://www.amazon.com/dp/B0CFWHPJTN,4.8,0,1.99,False,29,True,False,False,2023-09-15,Nonfiction
133100,B0C1KMFXJC,War And Peace,Leo Tolstoy,De Marque,https://m.media-amazon.com/images/I/715QpZlzmi...,https://www.amazon.com/dp/B0C1KMFXJC,4.7,0,0.00,False,29,True,False,False,2023-08-25,Nonfiction
133101,B0BS1KYZB6,Pride and Prejudice,Jane Austen,De Marque,https://m.media-amazon.com/images/I/81Scutrtj4...,https://www.amazon.com/dp/B0BS1KYZB6,4.7,0,0.00,False,29,False,False,False,2023-10-01,Nonfiction

In [162]:
#lendo as 28 primeiras linhas do DataFrame
livros.head(28)

,asin,title,author,soldBy,stars,reviews,price,isKindleUnlimited,category_id,isBestSeller,isEditorsPick,isGoodReadsChoice,publishedDate,category_name
0,B00TZE87S4,Adult Children of Emotionally Immature Parents...,Lindsay C. Gibson,Amazon.com Services LLC,4.8,0,9.99,False,6,True,False,False,2015-06-01,Parenting & Relationships
1,B08WCKY8MB,"From Strength to Strength: Finding Success, Ha...",Arthur C. Brooks,Penguin Group (USA) LLC,4.4,0,16.99,False,6,False,False,False,2022-02-15,Parenting & Relationships
2,B09KPS84CJ,Good Inside: A Guide to Becoming the Parent Yo...,Becky Kennedy,HarperCollins Publishers,4.8,0,16.99,False,6,False,True,False,2022-09-13,Parenting & Relationships
3,B07S7QPG6J,Everything I Know About Love: A Memoir,Dolly Alderton,HarperCollins Publishers,4.2,0,9.95,True,6,False,True,False,2020-02-25,Parenting & Relationships
4,B00N6PEQV0,The Seven Principles for Making Marriage Work:...,John Gottman,Random House LLC,4.7,0,13.99,False,6,False,False,False,2015-05-05,Parenting & Relationships
5,B000OVLKMM,The Glass Castle: A Memoir,Jeannette Walls,Simon and Schuster Digital Sales Inc,4.6,0,13.99,False,6,False,False,False,2005-03-01,Parenting & Relationships
6,B00AEBEQUK,Expecting Better: Why the Conventional Pregnan...,Emily Oster,Penguin Group (USA) LLC,4.6,0,14.99,False,6,True,False,False,NaN,Parenting & Relationships
7,B0BN5742KY,Never Enough: When Achievement Culture Becomes...,Jennifer Breheny Wallace,Penguin Group (USA) LLC,4.6,0,15.99,False,6,False,True,False,2023-08-22,Parenting & Relationships
8,B098PXH8CK,Unmasking Autism: Discovering the New Faces of...,Devon Price,Random House LLC,4.7,0,12.99,False,6,True,False,False,2022-04-05,Parenting & Relationships
9,B087D5YQXB,What Happened to You?: Conversations on Trauma...,Oprah Winfrey,Macmillan,4.7,0,14.99,True,6,False,True,False,2021-04-27,Parenting & Relationships
10,B00AN2JPNI,Moms on Call | Basic Baby Care 0-6 Months | Pa...,Laura Hunter LPN,Amazon.com Services LLC,4.7,0,24.99,False,6,False,False,False,NaN,Parenting & Relationships
11,B0B69SQNJY,A Little Pinprick (Rainey Paxton Series Book 1),Paige Dearth,Amazon.com Services LLC,4.6,0,5.99,True,6,True,False,False,NaN,Parenting & Relationships
12,B07FZPTDJ3,"Cribsheet: A Data-Driven Guide to Better, More...",Emily Oster,Penguin Group (USA) LLC,4.7,0,14.99,False,6,False,False,False,NaN,Parenting & Relationships
13,B0BN4RB7L9,The Daddy Diaries: The Year I Grew Up,Andy Cohen,Macmillan,4.5,0,14.99,False,6,False,False,False,2023-05-09,Parenting & Relationships
14,B0BNWSS8H3,"The Cruise: The brand new feel good, funny rea...",Caroline James,HarperCollins Publishers,4.2,0,2.99,False,6,False,False,False,2023-04-20,Parenting & Relationships
15,B0B3Y8QQ6R,You Could Make This Place Beautiful: A Memoir,Maggie Smith,Simon and Schuster Digital Sales Inc,4.5,0,14.99,False,6,False,True,False,2023-04-11,Parenting & Relationships
16,B004J4X32U,The Whole-Brain Child: 12 Revolutionary Strate...,Daniel J. Siegel,Random House LLC,4.7,0,12.99,False,6,False,False,False,2011-10-04,Parenting & Relationships
17,B0CBL7RV55,It Starts with the Egg: How the Science of Egg...,Rebecca Fett,Amazon.com Services LLC,4.7,0,9.99,False,6,True,False,False,NaN,Parenting & Relationships
18,B07JKJCWGY,The Girls Are Gone: The True Story of Two Sist...,Michael Brodkorb,Amazon.com Services LLC,3.9,0,0.00,False,6,True,False,False,2018-10-23,Parenting & Relationships
19,B01DCHZE3A,What to Expect When You're Expecting,Heidi Murkoff,Hachette Book Group,4.8,0,11.99,False,6,False,False,False,NaN,Parenting & Relationships
20,B004C438CW,No More Mr. Nice Guy,Robert Glover,Amazon.com Services LLC,4.6,0,9.99,False,6,False,False,False,2010-11-10,Parenting & Relationships
21,B001EGQNCI,The Color of Water,James McBride,Penguin Group (USA) LLC,4.6,0,12.99,False,6,False,False,False,2006-02-07,Parenting & Relationships
22,B00V3L8YSU,Oh Crap! Potty Training: Everything Modern Par...,Jamie Glowacki,Simon and Schuster Digital Sales Inc,4.5,0,13.99,False,6,False,False,False,NaN,Parenting & Relationships
23,B08F5L14MY,"Polysecure: Attachment, Trauma and Consensual ...",Jessica Fern,Amazon.com Services LLC,4.7,0,10.49,False,6,False,False,False,2020-10-23,Parenting & Relationships
24,B0C4Q6K148,Beyond the Game: A Surprise Pregnancy Sports R...,Susan Renee,Amazon.com Services LLC,4.2,0,4.99,True,6,True,False,False,NaN,Parenting & Relationships
25,B08X4XQXXK,Vax-Unvax: Let the Science Speak (Children’s H...,Robert F. Kennedy Jr.,Simon & Schuster Digital Sales Inc.,4.7,0,16.99,False,6,False,False,False,2023-08-29,Parenting & Relationships
26,B000Q9J0RO,Why Does He Do That?: Inside the Minds of Angr...,Lundy Bancroft,Penguin Group (USA) LLC,4.7,0,14.99,False,6,False,False,False,2003-09-02,Parenting & Relationships
27,B08BZX94C2,"Hunt, Gather, Parent: What Ancient Cultures Ca...",Michaeleen Doucleff,Simon and Schuster Digital Sales Inc,4.7,0,14.99,False,6,False,False,False,2021-03-02,Parenting & Relationships

In [164]:
#lendo as 28 últimas linhas do DataFrame
livros.tail(28)

,asin,title,author,soldBy,stars,reviews,price,isKindleUnlimited,category_id,isBestSeller,isEditorsPick,isGoodReadsChoice,publishedDate,category_name
133074,B08BNMVF1V,Legacy (Stoneblood Saga Book 7),Robyn Wideman,NaN,4.5,0,3.99,True,25,False,False,False,2020-07-18,Children's eBooks
133075,B002EDTV7Y,"Star Wars: Jedi Quest, Book 1: The Way of the ...",Jude Watson,NaN,4.4,0,0.00,True,25,False,False,False,NaN,Children's eBooks
133076,B007032W60,The Hunger Games Tribute Guide,Suzanne Collins,NaN,3.9,0,4.99,False,25,False,False,False,2012-02-07,Children's eBooks
133077,159052750X,"Kingdom's Call (Kingdom, Book 4)",Chuck Black,NaN,4.8,0,9.89,False,25,False,False,False,2007-05-15,Children's eBooks
133078,0692366903,Ultimate Minecraft Secrets: An Unofficial Guid...,Zack Zombie Books,NaN,4.4,0,8.99,True,25,False,False,False,2015-01-09,Children's eBooks
133079,B001KW7NZM,In the Belly of the Bloodhound: Bloody Jack #4,L. A. Meyer,NaN,4.8,0,0.00,False,25,False,False,False,NaN,Children's eBooks
133080,0807545465,The Lighthouse Mystery (The Boxcar Children My...,Gertrude Chandler Warner,NaN,4.6,0,6.98,False,25,False,False,False,1990-01-01,Children's eBooks
133081,1616559462,Plants vs. Zombies: Garden Warfare,Paul Tobin,NaN,4.7,0,8.49,False,25,False,False,False,2016-02-02,Children's eBooks
133082,1338863479,Dragon Pet (Diary of a Roblox Pro #2: An AFK B...,Ari Avatar,NaN,4.8,0,3.99,False,25,False,False,False,2023-03-07,Children's eBooks
133083,1338565311,The Silver Swamp: A Branches Book (The Last Fi...,Katrina Charman,NaN,4.8,0,2.99,False,25,False,False,False,2020-06-02,Children's eBooks
133084,B00Y79Y952,The Mark of the Horse Lord (Rediscovered Class...,Rosemary Sutcliff,NaN,4.4,0,8.99,False,25,False,False,False,2015-07-01,Children's eBooks
133085,149641053X,Hands-On Bible 365 Devotions for Kids: Faith-F...,Jennifer Hooks,NaN,4.8,0,14.99,False,25,False,False,False,2018-09-04,Children's eBooks
133086,B08ZYRQL65,Ashes of Flame: The Dragon Mafia Chronicles Bo...,Lela Grayce,NaN,4.4,0,3.99,True,25,False,False,False,2021-04-30,Children's eBooks
133087,0553536532,Finding Audrey,Sophie Kinsella,NaN,4.1,0,10.99,False,25,False,True,False,2016-05-03,Children's eBooks
133088,1338746758,Snow Day: A Graphic Novel (Mr. Wolf's Class #5),Aron Nels Steinke,NaN,4.7,0,8.49,False,25,False,False,False,2022-04-05,Children's eBooks
133089,1442428805,A Solitary Blue (3) (The Tillerman Cycle),Cynthia Voigt,NaN,4.6,0,11.99,False,25,False,False,False,2012-03-06,Children's eBooks
133090,B00HG1NG2U,Baby-sitters' European Vacation (Baby-Sitters ...,NaN,NaN,4.7,0,4.99,False,25,False,False,False,2022-08-17,Children's eBooks
133091,1524739030,The Kingdom of Back,Marie Lu,NaN,4.3,0,11.99,False,25,False,False,False,2021-03-02,Children's eBooks
133092,0142417823,The Batboy,Mike Lupica,NaN,4.7,0,7.99,False,25,False,False,False,2011-02-22,Children's eBooks
133093,B0C9MJNKY3,The Dream: The Extraordinary Revelation Of Who...,David Icke,Amazon.com Services LLC,4.5,0,7.99,False,29,False,False,False,2023-09-01,Nonfiction
133094,B08WRF7W4Z,Killers of the Flower Moon: Adapted for Young ...,David Grann,Random House LLC,4.6,0,9.99,False,29,False,True,False,2021-11-16,Nonfiction
133095,B09V1T7V5C,THE EYES OF DARKNESS,Dean Koontz,Amazon.com Services LLC,4.4,0,9.99,True,29,False,False,False,2022-03-05,Nonfiction
133096,B08BR2HFWJ,Everything Sad Is Untrue: (a true story),Daniel Nayeri,Amazon.com Services LLC,4.6,0,8.80,False,29,False,False,False,2020-08-25,Nonfiction
133097,B0C3SJDLK8,Anna Karenina,Leo Tolstoy,De Marque,4.7,0,0.00,False,29,True,False,False,2023-09-15,Nonfiction
133098,B09DW752Y1,Scary Smart: Scary Smart: The Future of Artifi...,Mo Gawdat,Amazon.com Services LLC,4.4,0,9.99,False,29,False,False,False,2021-09-30,Nonfiction
133099,B0CFWHPJTN,The Count of Monte Cristo: The Original Unabri...,Alexandre Dumas,De Marque,4.8,0,1.99,False,29,True,False,False,2023-09-15,Nonfiction
133100,B0C1KMFXJC,War And Peace,Leo Tolstoy,De Marque,4.7,0,0.00,False,29,True,False,False,2023-08-25,Nonfiction
133101,B0BS1KYZB6,Pride and Prejudice,Jane Austen,De Marque,4.7,0,0.00,False,29,False,False,False,2023-10-01,Nonfiction

In [11]:
#informações sobre o DataFrame, tipos de dados,  valores não nulos e memória utilizada
livros.info()

## >>> demonstrou que as colunas autor, vendedor e data da publicação possui valores nulos, 
# concentrando a maior diferença na coluna data da publicação.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133102 entries, 0 to 133101
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   asin               133102 non-null  object
 1   title              133102 non-null  object
 2   author             132677 non-null  object
 3   soldBy             123869 non-null  object
 4   imgUrl             133102 non-null  object
 5   productURL         133102 non-null  object
 6   stars              133102 non-null  float64
 7   reviews            133102 non-null  int64
 8   price              133102 non-null  float64
 9   isKindleUnlimited  133102 non-null  bool
 10  category_id        133102 non-null  int64
 11  isBestSeller       133102 non-null  bool
 12  isEditorsPick      133102 non-null  bool
 13  isGoodReadsChoice  133102 non-null  bool
 14  publishedDate      84086 non-null   object
 15  category_name      133102 non-null  object
dtypes: bool(4), float64(2), int64(2), object(8)
memory usage: 12.7+ MB

In [13]:
#qtde de valores nulos por coluna

livros.isnull().sum()

## >>> confirma a análise anterior: qtde de valores nulos em autor, vendedor e data da publicação.

asin                     0
title                    0
author                 425
soldBy                9233
imgUrl                   0
productURL               0
stars                    0
reviews                  0
price                    0
isKindleUnlimited        0
category_id              0
isBestSeller             0
isEditorsPick            0
isGoodReadsChoice        0
publishedDate        49016
category_name            0
dtype: int64

In [167]:
#percentual de nulos em comparação com o total de linhas do DataFrame

(livros.isnull().sum()/livros.shape[0])*100

## >> comparando com o DataFrame, o percentual de valores nulos em autor e vendedor são baixos,
# mas em data da publicação tem percentual significativo, porém não impacta diretamente na análise.

asin                  0.000000
title                 0.000000
author                0.319304
soldBy                6.936785
stars                 0.000000
reviews               0.000000
price                 0.000000
isKindleUnlimited     0.000000
category_id           0.000000
isBestSeller          0.000000
isEditorsPick         0.000000
isGoodReadsChoice     0.000000
publishedDate        36.825893
category_name         0.000000
dtype: float64

In [7]:
#dataframe possui campos com link's não necessários para a análise

livros[['imgUrl','productURL']]

,imgUrl,productURL
0,https://m.media-amazon.com/images/I/713KZTsaYp...,https://www.amazon.com/dp/B00TZE87S4
1,https://m.media-amazon.com/images/I/A1LZcJFs9E...,https://www.amazon.com/dp/B08WCKY8MB
2,https://m.media-amazon.com/images/I/71RIWM0sv6...,https://www.amazon.com/dp/B09KPS84CJ
3,https://m.media-amazon.com/images/I/71QdQpTiKZ...,https://www.amazon.com/dp/B07S7QPG6J
4,https://m.media-amazon.com/images/I/813o4WOs+w...,https://www.amazon.com/dp/B00N6PEQV0
...,...,...
133097,https://m.media-amazon.com/images/I/61RXEyMctk...,https://www.amazon.com/dp/B0C3SJDLK8
133098,https://m.media-amazon.com/images/I/71tjf6R-Wa...,https://www.amazon.com/dp/B09DW752Y1
133099,https://m.media-amazon.com/images/I/71zcCb5Pvu...,https://www.amazon.com/dp/B0CFWHPJTN
133100,https://m.media-amazon.com/images/I/715QpZlzmi...,https://www.amazon.com/dp/B0C1KMFXJC
133101,https://m.media-amazon.com/images/I/81Scutrtj4...,https://www.amazon.com/dp/B0BS1KYZB6

In [8]:
# deletando as colunas imgUrl e productURL do DataFrame.

livros.drop(columns = ['imgUrl','productURL'], inplace = True)

In [9]:
livros.shape

(133102, 14)

In [83]:
#qtde de livros por categoria (28 categorias com mais livros)

livros[['category_name']].value_counts().head(28)

category_name
Mystery, Thriller & Suspense    6272
Engineering & Transportation    6162
Science & Math                  5955
Parenting & Relationships       5901
Children's eBooks               5747
Teen & Young Adult              5738
Foreign Language                5724
Travel                          5526
LGBTQ+ eBooks                   5517
Computers & Technology          5504
Crafts, Hobbies & Home          5502
Biographies & Memoirs           5405
Cookbooks, Food & Wine          5333
Law                             5027
Education & Teaching            4986
Religion & Spirituality         4970
Arts & Photo graphy             4916
Politics & Social Sciences      4207
Literature & Fiction            4152
Humor & Entertainment           4095
Science Fiction & Fantasy       3995
Self-Help                       3493
Reference                       3388
Sports & Outdoors               3206
Medical                         2583
Business & Money                2577
Romance                         2214
History                         2045
Name: count, dtype: int64

In [147]:
#qtde de livros por autor (28 autores com mais livros)

livros[['author']].value_counts().head(28)

author
James Patterson            212
DK Eyewitness              163
DK                         155
Captivating History        120
Fodor's Travel Guides      115
Erin Hunter                114
J.K. Rowling               113
Hourly History             103
America's Test Kitchen      99
Stephen King                99
Nora Roberts                99
Rick Riordan                93
Terry Pratchett             90
Dianne Harman               86
Olly Richards               83
Rick Steves                 76
Lincoln Peirce              76
Mary Stone                  76
Brandon Sanderson           76
Rough Guides                73
Michael Anderle             73
Lingo Mastery               70
Amazon.com Services LLC     68
Jessie Gussman              65
John Grisham                64
J.N. Chaney                 64
J. D. Robb                  62
Amanda M. Lee               60
Name: count, dtype: int64

In [146]:
#qtde de livros que cada vendedor vendeu (28 maiores vendedores)

livros[['soldBy']].value_counts().head(28)

soldBy
Amazon.com Services LLC                    84759
Random House LLC                            5872
Hachette Book Group                         4736
Penguin Group (USA) LLC                     4385
HarperCollins Publishers                    4328
Macmillan                                   3147
Simon and Schuster Digital Sales Inc        3047
Penguin Random House Publisher Services     2390
JOHN WILEY AND SONS INC                     2386
Simon & Schuster Digital Sales Inc.         1748
Pearson Education,Inc.                      1312
HarperCollins Publishing                    1132
Penguin Random House Grupo Editorial         944
Cengage Learning                             750
Editorial Planeta, S.A.U.                    605
Harlequin Digital Sales Corp.                440
PRH UK                                       358
Macmillan Higher Education                   212
De Marque                                    194
Yen Press LLC                                162
Disney Book Group                            133
W. W. Norton & Company                       120
Harper Collins                               114
Scholastic Trade Publisher                   102
Marvel Entertainment US                       90
Games Workshop                                79
INTERFORUM                                    48
Random House ZA                               45
Name: count, dtype: int64

In [145]:
# valor arrecadado com a venda dos livros

livros[['price']].sum()

price    2014382.61
dtype: float64

In [144]:
# valor total dos livros vendidos por cada vendedor, ordenado do maior para o menor (28 maiores vendedores)

livros.groupby(["soldBy"])["price"].sum().sort_values(ascending=False).head(28)

soldBy
Amazon.com Services LLC                    1283012.91
JOHN WILEY AND SONS INC                     103699.03
Pearson Education,Inc.                       99838.82
Random House LLC                             67173.43
HarperCollins Publishers                     56847.96
Hachette Book Group                          51137.06
Penguin Group (USA) LLC                      50335.15
Simon and Schuster Digital Sales Inc         41112.28
Macmillan                                    38268.68
Penguin Random House Publisher Services      34824.20
Cengage Learning                             33366.98
Simon & Schuster Digital Sales Inc.          27772.07
HarperCollins Publishing                     14726.47
Macmillan Higher Education                    8762.34
Penguin Random House Grupo Editorial          8718.61
W. W. Norton & Company                        5711.85
Editorial Planeta, S.A.U.                     5628.95
PRH UK                                        4552.92
Harlequin Digital Sales Corp.                 4324.10
Disney Book Group                             1555.18
De Marque                                     1499.19
Yen Press LLC                                 1370.38
Marvel Entertainment US                       1160.15
Games Workshop                                1052.21
Scholastic Trade Publisher                     932.98
Harper Collins                                 914.36
EDIGITA                                        800.76
INTERFORUM                                     747.52
Name: price, dtype: float64

In [143]:
#qtde de livros que são best-sellers e que não são best-sellers

livros['isBestSeller'].value_counts()

isBestSeller
False    130866
True       2236
Name: count, dtype: int64

In [158]:
# valor arrecadado por livros que são best-sellers e que não são best-sellers

livros.groupby(["isBestSeller"])["price"].sum()

isBestSeller
False    1997207.34
True       17175.27
Name: price, dtype: float64

In [ ]:
#qtde de livros que são best-sellers de autor (28 autores com mais livros best-sellers)

bestseller = livros[livros['isBestSeller'] == True]['author'].value_counts().head(28)
bestseller

author
J.K. Rowling           16
DK                     10
Captivating History     7
Paul Levine             7
Freida McFadden         7
Explore ToWin           6
Paige Dearth            6
C.W. Farnsworth         6
Bill O'Reilly           5
Marcus Aurelius         5
William Bernhardt       5
Hourly History          4
FX Holden               4
LCF Publishing          4
Disney Book Group       4
M. Mastenbjörk M.D.     4
Lonely Planet           4
Damon Zahariades        4
Shari Low               4
Alex G. Rasiwas         3
Delara Chowdhury        3
Olly Richards           3
Mark Sloan              3
Mark Reed               3
Jana Petken             3
Oliver Powell           3
Damon Ferrante          3
Louise Davidson         3
Name: count, dtype: int64

In [ ]:
#qtde de livros que não são best-sellers de autor (28 autores com mais livros que não são best-sellers)

naobestseller = livros[~livros['isBestSeller']]['author'].value_counts().head(28)
naobestseller

author
James Patterson            209
DK Eyewitness              163
DK                         145
Fodor's Travel Guides      115
Erin Hunter                114
Captivating History        113
Hourly History              99
Nora Roberts                99
America's Test Kitchen      99
Stephen King                98
J.K. Rowling                97
Rick Riordan                90
Terry Pratchett             90
Dianne Harman               83
Olly Richards               80
Brandon Sanderson           76
Rick Steves                 75
Lincoln Peirce              75
Mary Stone                  75
Michael Anderle             73
Rough Guides                73
Lingo Mastery               69
Amazon.com Services LLC     68
Jessie Gussman              63
J.N. Chaney                 63
John Grisham                63
J. D. Robb                  62
Amanda M. Lee               60
Name: count, dtype: int64

In [168]:
# média e valor total arrecadado por livros que são best-sellers e que não são best-sellers

livros.groupby(["isBestSeller"])["price"].agg(["mean", "sum"]).round(2)

               mean         sum
isBestSeller
False         15.26  1997207.34
True           7.68    17175.27

In [172]:
# média e valor total arrecadado por livros vendidos por cada vendedor, 
# ordenado pelo valor total (28 maiores vendedores)

livros.groupby(["soldBy"])["price"].agg(["mean", "sum"]).sort_values("sum", ascending=False).round(2).head(28)

                                          mean         sum
soldBy
Amazon.com Services LLC                  15.14  1283012.91
JOHN WILEY AND SONS INC                  43.46   103699.03
Pearson Education,Inc.                   76.10    99838.82
Random House LLC                         11.44    67173.43
HarperCollins Publishers                 13.13    56847.96
Hachette Book Group                      10.80    51137.06
Penguin Group (USA) LLC                  11.48    50335.15
Simon and Schuster Digital Sales Inc     13.49    41112.28
Macmillan                                12.16    38268.68
Penguin Random House Publisher Services  14.57    34824.20
Cengage Learning                         44.49    33366.98
Simon & Schuster Digital Sales Inc.      15.89    27772.07
HarperCollins Publishing                 13.01    14726.47
Macmillan Higher Education               41.33     8762.34
Penguin Random House Grupo Editorial      9.24     8718.61
W. W. Norton & Company                   47.60     5711.85
Editorial Planeta, S.A.U.                 9.30     5628.95
PRH UK                                   12.72     4552.92
Harlequin Digital Sales Corp.             9.83     4324.10
Disney Book Group                        11.69     1555.18
De Marque                                 7.73     1499.19
Yen Press LLC                             8.46     1370.38
Marvel Entertainment US                  12.89     1160.15
Games Workshop                           13.32     1052.21
Scholastic Trade Publisher                9.15      932.98
Harper Collins                            8.02      914.36
EDIGITA                                  33.36      800.76
INTERFORUM                               15.57      747.52

In [173]:
# média e valor total arrecadado por livros vendidos de cada autor,
# ordenado pelo valor total (28 maiores autores)

livros.groupby(["author"])["price"].agg(["mean", "sum"]).sort_values("sum", ascending=False).round(2).head(28)

                                                    mean      sum
author
StatPearls Publishing LLC                         187.94  4134.78
James Patterson                                     9.17  1943.86
Erwin Chemerinsky                                 105.81  1693.00
America's Test Kitchen                             16.35  1619.01
DK                                                 10.22  1583.47
LexisNexis Editorial Staff                        174.44  1569.95
Amazon.com Services LLC                            22.53  1531.72
DK Eyewitness                                       9.18  1496.41
Fodor's Travel Guides                              12.24  1407.23
Mometrix                                           51.28  1333.15
Deborah E. Bouchoux                               127.61  1276.09
Douglas J. Whaley                                 249.58  1247.91
American Academy of Orthopaedic Surgeons (AAOS),  173.46  1214.20
Steven L. Emanuel                                  52.65  1158.22
Stephen King                                       11.21  1109.42
J.K. Rowling                                        9.71  1096.99
Rick Steves                                        13.54  1029.24
Nora Roberts                                       10.09   999.04
Harvard Business Review                            15.87   936.53
James D. Halderman                                 68.07   884.87
Erin Hunter                                         7.62   868.73
Roger LeRoy Miller                                 54.12   865.84
Gary B. Born                                      279.45   838.34
CCPS (Center for Chemical Process Safety)         118.86   832.00
Leslie Joan Harris                                276.60   829.79
J. D. Robb                                         12.94   801.97
Lynn M. LoPucki                                   263.98   791.95
Galit Shmueli                                     113.00   791.00

In [98]:
livros

,asin,title,author,soldBy,stars,reviews,price,isKindleUnlimited,category_id,isBestSeller,isEditorsPick,isGoodReadsChoice,publishedDate,category_name
0,B00TZE87S4,Adult Children of Emotionally Immature Parents...,Lindsay C. Gibson,Amazon.com Services LLC,4.8,0,9.99,False,6,True,False,False,2015-06-01,Parenting & Relationships
1,B08WCKY8MB,"From Strength to Strength: Finding Success, Ha...",Arthur C. Brooks,Penguin Group (USA) LLC,4.4,0,16.99,False,6,False,False,False,2022-02-15,Parenting & Relationships
2,B09KPS84CJ,Good Inside: A Guide to Becoming the Parent Yo...,Becky Kennedy,HarperCollins Publishers,4.8,0,16.99,False,6,False,True,False,2022-09-13,Parenting & Relationships
3,B07S7QPG6J,Everything I Know About Love: A Memoir,Dolly Alderton,HarperCollins Publishers,4.2,0,9.95,True,6,False,True,False,2020-02-25,Parenting & Relationships
4,B00N6PEQV0,The Seven Principles for Making Marriage Work:...,John Gottman,Random House LLC,4.7,0,13.99,False,6,False,False,False,2015-05-05,Parenting & Relationships
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133097,B0C3SJDLK8,Anna Karenina,Leo Tolstoy,De Marque,4.7,0,0.00,False,29,True,False,False,2023-09-15,Nonfiction
133098,B09DW752Y1,Scary Smart: Scary Smart: The Future of Artifi...,Mo Gawdat,Amazon.com Services LLC,4.4,0,9.99,False,29,False,False,False,2021-09-30,Nonfiction
133099,B0CFWHPJTN,The Count of Monte Cristo: The Original Unabri...,Alexandre Dumas,De Marque,4.8,0,1.99,False,29,True,False,False,2023-09-15,Nonfiction
133100,B0C1KMFXJC,War And Peace,Leo Tolstoy,De Marque,4.7,0,0.00,False,29,True,False,False,2023-08-25,Nonfiction
133101,B0BS1KYZB6,Pride and Prejudice,Jane Austen,De Marque,4.7,0,0.00,False,29,False,False,False,2023-10-01,Nonfiction